import os
import asyncio
import edge_tts
import whisper
import sounddevice as sd
from scipy.io.wavfile import write

class AudioManager:
    def __init__(self):
        # Define available voices
        self.voices = {
            "male": "en-US-ChristopherNeural",
            "female": "en-US-AriaNeural",  
            "ind_male": "en-IN-PrabhatNeural",
            "ind_female": "en-IN-NeerjaNeural",
            "ind_child": "en-IN-PrabhatNeural", # Note: EdgeTTS doesn't have explicit 'child' voices, reusing Prabhat
            "british_male": "en-GB-RyanNeural",
            "british_female": "en-GB-SoniaNeural"
        }
        
        # Load the Whisper model locally
        print("🎧 Loading Whisper Model... (this happens once)")
        self.transcriber = whisper.load_model("base")

    async def generate_voiceover(self, text: str, output_path: str, voice_type="ind_male", rate="+0%") -> str:
        """
        Converts text to audio with custom voice and speed.
        """
        selected_voice = self.voices.get(voice_type, "en-US-ChristopherNeural")
        print(f"🗣️ Generating ({voice_type} | {rate}): '{text[:30]}...'")
        communicate = edge_tts.Communicate(text, selected_voice, rate=rate)
        await communicate.save(output_path)
        
        if os.path.exists(output_path):
            return output_path
        else:
            raise FileNotFoundError("❌ Failed to generate voiceover file.")

    def record_audio_from_mic(self, output_path: str, duration_sec=5):
        """
        Records audio from the default microphone for a set duration.
        """
        fs = 44100  # Sample rate
        print(f"🎤 Recording for {duration_sec} seconds... speak now!")
        
        # Capture audio
        myrecording = sd.rec(int(duration_sec * fs), samplerate=fs, channels=1)
        sd.wait()  # Wait until recording is finished
        
        # Save as WAV file
        print(f"💾 Saving recording to {output_path}...")
        write(output_path, fs, myrecording)  # Save as WAV file 
        return output_path

    def transcribe_audio(self, audio_path: str):
        """
        Extracts text from audio with precise timestamps.
        """
        print(f"📝 Transcribing audio: {os.path.basename(audio_path)}...")
        # Whisper works best with 16kHz, but handles 44.1kHz fine usually.
        # Ensure file exists
        if not os.path.exists(audio_path):
            raise FileNotFoundError(f"Audio file not found: {audio_path}")
            
        result = self.transcriber.transcribe(audio_path)
        return result

# --- Updated Testing Block ---
if __name__ == "__main__":
    # Ensure assets/temp exists
    temp_folder = os.path.join("assets", "temp")
    os.makedirs(temp_folder, exist_ok=True)
    
    manager = AudioManager()
    
    # Define paths
    tts_output = os.path.join(temp_folder, "test_tts.mp3")
    mic_output = os.path.join(temp_folder, "test_mic.wav")

    print("\n--- TEST MENU ---")
    print("1. Test Text-to-Speech (TTS)")
    print("2. Test Microphone Recording & Transcription")
    choice = input("Enter choice (1 or 2): ")

    if choice == "1":
        text_input = "This is the Test AI Video generated by Clipflow."
        try:
            asyncio.run(manager.generate_voiceover(
                text=text_input, 
                output_path=tts_output, 
                voice_type="ind_male", 
                rate="+10%"
            ))
            print(f"✅ TTS Audio saved at: {tts_output}")
            res = manager.transcribe_audio(tts_output)
            print(f"📝 Transcription: {res['text']}")
        except Exception as e:
            print(f"❌ Error: {e}")

    elif choice == "2":
        try:
            # Record
            input("Press Enter to start recording (5 seconds)...")
            manager.record_audio_from_mic(mic_output, duration_sec=5)
            
            # Transcribe
            print("⏳ Analyzing your voice...")
            res = manager.transcribe_audio(mic_output)
            print(f"\n📝 YOUR VOICE SAID: \"{res['text']}\"")
        except Exception as e:
            print(f"❌ Error: {e}")